name: Deploy to AWS Linux Server
on:
  push:
    branches:
      - git-test
jobs:
  deploy:
    runs-on: self-hosted
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
    - name: Install AWS CLI
      run: |
        sudo apt-get update
        sudo apt-get install -y awscli
    - name: Deploy code
      run: |
        aws configure set aws_access_key_id ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws configure set aws_secret_access_key ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws configure set region ${{ secrets.AWS_REGION }}
        # aws s3 sync . s3://${{ secrets.S3_BUCKET }} --delete
        ssh ${{ secrets.SERVER_USER }}@${{ secrets.SERVER_IP }}
        cd /home/ubuntu/hello-world
        ls -la
        git remote -v
        git checkout alpha
        git pull
        git branch
